//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Entrypanel_prefab
    {
        public const string BundleName = "entrypanel_prefab";
        public const string ENTRYPANEL = "entrypanel";
    }
    public class Exitpanel_prefab
    {
        public const string BundleName = "exitpanel_prefab";
        public const string EXITPANEL = "exitpanel";
    }
    public class Lost_touch_mp3
    {
        public const string BundleName = "lost touch_mp3";
        public const string LOST_TOUCH = "lost touch";
    }
    public class Mainpanel_prefab
    {
        public const string BundleName = "mainpanel_prefab";
        public const string MAINPANEL = "mainpanel";
    }
    public class Setingpanel_prefab
    {
        public const string BundleName = "setingpanel_prefab";
        public const string SETINGPANEL = "setingpanel";
    }
}
